#!/bin/bash
set -e  # don't allow errors to fail silently
echo `which pip`  # in case the wrong `pip` is used, this will let us debug
pip install -e git@github.com:ga4gh/vrs-python.git # install the custom library

